### ISSUE TITLE
Method Add : Implement a double-down function

### ISSUE THREAD

**Issue by Yeon-Hun** [Yeon-Hun/RC_BlackJack#1]
더블 다운 기능 추가 해야함

**Comment by mosa7410** [comment]
double down 기능 추가
완료 6/15 23:00

**Comment by Yeon-Hun** [comment]
더블다운은 한장을 무조건 받아야 하는데 안받고 스탠드 하는 경우가 있음

*더블다운(DOUBLE DOWN)
두장의 패를 가진상태에서 돈을 두배를 걸며 한장의 카드만을 더 가지고 오는 룰입니다. 더블 다운(DOUBLE DOWN)을 하면 무조건 1장을 받아와야합니다.(그래서 처음 두장의 합이 10 또는 11일때 더블 다운을 많이합니다.)

출처: http://richrich1.tistory.com/22 [생각없이살기]

**Comment by mosa7410** [comment]
더블 다운을 클릭하면 무조건 카드 한장을 받고 게임을 끝낸다.
