### ISSUE TITLE
[버그 수정] 유저의 점수가 21이 넘어가면 무조건 져야 한다.

### ISSUE THREAD

**Issue by Yeon-Hun** [Yeon-Hun/RC_BlackJack#12]
현재는 21이 넘어도 딜러의 점수가 높으면 이기는 것으로 처리됨

**Comment by ampo2787** [comment]
6/4 13:50 카드를 더 뽑지는 않지만 버튼도 게임 종료된 상태로 나오게 바꿔야 할 듯함.

**Comment by Yeon-Hun** [comment]
점수 계산 코드 오작동 하는부분 있어서 다시 수정해야함
